image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/h5ai
  tag: latest@sha256:33a8a6f1ef11cf01dc6cf8aa70f7fbbe22879e16b14da790b32b6c41a15253e6
persistence:
  config:
    enabled: true
    mountPath: /config
  directorystorage:
    enabled: true
    mountPath: /h5ai
    readOnly: true
service:
  main:
    ports:
      main:
        port: 80
        protocol: tcp
        targetPort: 80
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
