image:
  repository: tccr.io/truecharts/kavitaemail
  pullPolicy: IfNotPresent
  tag: 0.1.14@sha256:113b8a199cd671d6b418ca9c2819c8d3374b69bcd72ef0a82530c7b48d74ab08
service:
  main:
    ports:
      main:
        protocol: http
        port: 15003
        targetPort: 5003
persistence:
  config:
    enabled: false
    mountPath: /app/config
portal:
  open:
    enabled: false
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        env:
          DISP_NAME: kavita
          SMTP_HOST: ""
          SMTP_PORT: 587
          SEND_ADDR: ""
          SMTP_USER: ""
          SMTP_PASS: ""
