image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/bitcoin-node
  tag: latest@sha256:ef1d0c639cded75166c2141c198d68a2cff5a40af1d0bb875b56dbb66ac426c1
persistence:
  blockhainstorage:
    enabled: true
    mountPath: /bitcoin/.bitcoin
service:
  main:
    ports:
      main:
        port: 8332
        protocol: tcp
        targetPort: 8332
  port2:
    enabled: true
    ports:
      port2:
        enabled: true
        port: 8333
        protocol: tcp
        targetPort: 8333
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
