image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/suistartpage
  tag: latest@sha256:ff558229637988720cf6e3ab888b4e7b2642b4a5fddfc3378fbb91d68636a2c9
persistence:
  appdata:
    enabled: true
    mountPath: /usr/share/nginx/html
service:
  main:
    ports:
      main:
        port: 8489
        protocol: tcp
        targetPort: 80
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
