image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/urban-terror
  tag: latest@sha256:d60c9de2ef6c9a549bd01540efd56b4c889f5e713c1685205624e5e19887cdc5
persistence:
  datadir:
    enabled: true
    mountPath: /urbanterror
service:
  main:
    ports:
      main:
        port: 27960
        protocol: udp
        targetPort: 27960
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env:
          CHECK_FOR_UPDATES: "true"
          START_PARAMS: ""
          UMASK: "000"
