image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/stationeers
  tag: latest@sha256:00dcfb407c0dc9901e65481d437e3eb6b6dc78e9d57617ab2ab251b951db88f3
service:
  main:
    ports:
      main:
        port: 27015
        protocol: udp
        targetPort: 27015
  gameport:
    enabled: true
    ports:
      gameport:
        enabled: true
        port: 27500
        protocol: udp
        targetPort: 27500
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env:
          GAME_ID: "600760"
          GAME_PARAMS: AutoSave true SaveInterval 300
          VALIDATE: false
          USERNAME: ""
          PASSWRD: ""
