image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/conanexiles
  tag: latest@sha256:119f2b3296730c40f332175c2a8fbfbb427e024f11fe3a8531b3d410c365d427
service:
  main:
    ports:
      main:
        port: 7777
        protocol: udp
        targetPort: 7777
  gameport1:
    enabled: true
    ports:
      gameport1:
        enabled: true
        port: 7778
        protocol: udp
        targetPort: 7778
  steamport:
    enabled: true
    ports:
      steamport:
        enabled: true
        port: 27015
        protocol: udp
        targetPort: 27015
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env:
          GAME_ID: "443030"
          GAME_PARAMS: ""
          VALIDATE: false
          WS_CONTENT: ""
          USERNAME: ""
          PASSWRD: ""
