image:
  repository: tccr.io/truecharts/baikal
  pullPolicy: IfNotPresent
  tag: 0.9.3@sha256:ea5a098119a0b72ccc84baa22b7375bf81733cec4538e35346fe906452f2f9cf
service:
  main:
    ports:
      main:
        port: 10293
        protocol: http
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: /var/www/baikal/config
  specific:
    enabled: true
    mountPath: /var/www/baikal/Specific
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
