image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/counterstrike2d
  tag: latest@sha256:86580b1dba85da3ee01b53990a4cd514141bd878ee0fd72c961703cfe664c6b6
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
service:
  main:
    ports:
      main:
        port: 36963
        protocol: udp
        targetPort: 36963
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env:
          FORCE_UPDATE: ""
          GAME_PARAMS: ""
