image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/preclear
  tag: latest@sha256:417d95a952b25e042a93bb62813956e8ca7269f4e4b3e13d44e01c36fa18fdaa
persistence:
  config:
    enabled: true
    mountPath: /config
service:
  main:
    ports:
      main:
        port: 6080
        protocol: tcp
        targetPort: 6080
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          UMASK: "000"
          VNC_PASSWORD: ""
          WEBPAGE_TITLE: Preclear
