env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/pixelserv-tls
  tag: latest@sha256:64d7cf54725a9f10c05e893029ae8cded6a46fdac0148063e2969df5efc3877b
persistence:
  certficatesdir:
    enabled: true
    mountPath: /var/cache/pixelserv
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  http:
    enabled: true
    ports:
      http:
        enabled: true
        port: 80
        protocol: tcp
        targetPort: 80
  main:
    ports:
      main:
        port: 443
        protocol: http
        targetPort: 443

portal:
  open:
    enabled: true
