image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/dontstarvetogether
  tag: latest@sha256:4e6b786b097ab97d5dc0aeac7850024c655500d58ac40eb3386a4cde677e23a7

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

secretEnv:
  USERNAME: ""
  PASSWRD: ""

env:
  CAVES: "true"
  FORCE_X64: "true"
  GAME_ID: "343050"
  VALIDATE: false

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

service:
  main:
    ports:
      main:
        port: 10890
        protocol: udp
        targetPort: 10890
  authentication:
    enabled: true
    ports:
      authentication:
        enabled: true
        port: 8766
        protocol: udp
        targetPort: 8766
  masterserver:
    enabled: true
    ports:
      masterserver:
        enabled: true
        port: 27016
        protocol: udp
        targetPort: 27016

persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
  token:
    enabled: true
    mountPath: /serverdata/.klei/DoNotStarveTogether

portal:
  open:
    enabled: true
