image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/goaccess
  tag: latest@sha256:0bf7c94ed92a39f58ce83aff9cf6217d25b9298cb0b985d9c9171d29509d3f00
persistence:
  goaccess:
    enabled: true
    mountPath: /opt/log
service:
  main:
    ports:
      main:
        port: 7889
        protocol: tcp
        targetPort: 7889
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
