image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/keeweb
  tag: latest@sha256:0a32848c665a36a3c3e06fd97fa6cc2b929aaa158677344f24c8ce369b780f3b
service:
  main:
    ports:
      main:
        port: 8003
        protocol: https
        targetPort: 443
  http:
    enabled: true
    ports:
      http:
        enabled: true
        port: 8004
        protocol: http
        targetPort: 80
ingress:
  http:
    autoLink: true
persistence:
  nginx:
    enabled: true
    mountPath: /etc/nginx/external
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
