image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/root
  tag: latest@sha256:492397563d823255e7a3cb9ecbe7db089f59e5daba74d5a6a63af8a4c01dde5c
persistence:
  appdata:
    enabled: true
    mountPath: /appdata
service:
  main:
    ports:
      main:
        port: 9999
        protocol: tcp
        targetPort: 8888
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
