image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/duplicacy
  tag: latest@sha256:1c5a6f92d6856d1f8c56c47566f78a383b702e73a5cc573cd0b6fd5c6ea197c0
service:
  main:
    ports:
      main:
        port: 3875
        protocol: http
        targetPort: 3875
persistence:
  config:
    enabled: true
    mountPath: /config
  cache:
    enabled: true
    mountPath: /cache
  logs:
    enabled: true
    mountPath: /logs
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
