image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/daysofwar
  tag: latest@sha256:ed0d4ec874b08ec95802ebeef08a9729ca258b6b80e741984db47c3dc2821134
service:
  main:
    ports:
      main:
        port: 7777
        protocol: udp
        targetPort: 7777
  steamport:
    enabled: true
    ports:
      steamport:
        enabled: true
        port: 27015
        protocol: udp
        targetPort: 27015
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env:
          GAME_ID: "541790"
          GAME_PARAMS: dow_cathedral
          GAME_PORT: "7777"
          QUERY_PORT: "27015"
          VALIDATE: false
          USERNAME: ""
          PASSWRD: ""
