image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/remotely
  tag: latest@sha256:f443102cfc770a4a0e5c08870ec07147c60afde68deb6e7172ac2b96332a6f0f
persistence:
  data:
    enabled: true
    mountPath: /remotely-data
service:
  main:
    ports:
      main:
        port: 9280
        protocol: tcp
        targetPort: 5000
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
