image:
  repository: tccr.io/truecharts/cherry
  pullPolicy: IfNotPresent
  tag: 0.0.6@sha256:54a0c8574240d0df483de88a815da9f8e62a9048badde61271b6dd4f1c03909f
cherry:
  insecure_cookie: true
  public_registration: true
  page_bookmark_limit: 60
  google_oauth_uri: ""
  google_oauth_id: ""
  google_oauth_secret: ""
service:
  main:
    ports:
      main:
        port: 10303
        protocol: http
        targetPort: 8000
persistence:
  data:
    enabled: true
    mountPath: "/data"
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: HTTP
              path: /
            readiness:
              type: HTTP
              path: /
            startup:
              type: HTTP
              path: /
          envFrom:
            - secretRef:
                name: '{{ include "tc.v1.common.names.fullname" . }}-cherry-secret'
            - configMapRef:
                name: '{{ include "tc.v1.common.names.fullname" . }}-cherry-configmap'
