image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/snippet-box
  tag: latest@sha256:cddcb706538f65fcf69a2d86f30c400f2dddbf04ea65e9801b8376a5c6f3e5e1
persistence:
  data:
    enabled: true
    mountPath: /app/data
service:
  main:
    ports:
      main:
        port: 5039
        protocol: tcp
        targetPort: 5000
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
