image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/vertex
  tag: vstable@sha256:573768482ae7e0deb31e5f9feb84dded893960e87584254ace53bd4bfb08bfd8
persistence:
  config:
    enabled: true
    mountPath: /vertex
service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          PORT: "3000"
