image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/dvblink
  tag: latest@sha256:59cb771732ceaec8d7229c40769021bba76e03c10efd8f1973987de343061238
persistence:
  dvblink:
    enabled: true
    mountPath: /opt/DVBLink
service:
  main:
    ports:
      main:
        port: 39876
        protocol: http
        targetPort: 39876
  tcpport1:
    enabled: true
    ports:
      tcpport1:
        enabled: true
        port: 8100
        protocol: tcp
        targetPort: 8100
  tcpport2:
    enabled: true
    ports:
      tcpport2:
        enabled: true
        port: 2222
        protocol: tcp
        targetPort: 22
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
