image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/sinusbot
  tag: latest@sha256:94a8c36da24a010e0460f3426b994a7c6f02b0f7408c2d6168e7523bf82041c3
persistence:
  data:
    enabled: true
    mountPath: /opt/sinusbot/data
  scriptspath:
    enabled: true
    mountPath: /opt/sinusbot/scripts
service:
  main:
    ports:
      main:
        port: 8087
        protocol: tcp
        targetPort: 8087
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          OVERRIDE_PASSWORD: foobar
