image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/auto-yt-dl
  tag: latest@sha256:b63a64bb83a64e32da877bb45c24a6bf2f9a6a05aaa6833ff9ae10a321ac149e
persistence:
  data:
    enabled: true
    mountPath: /app/data
  hostpath1:
    enabled: true
    mountPath: /app/Downloads
service:
  main:
    ports:
      main:
        port: 5000
        protocol: tcp
        targetPort: 5000
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
