image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/craftopia
  tag: latest@sha256:7ff19f331c73859b7e4636e13e91beba1ec0b5d8803a09bad92851355e0d494b
service:
  main:
    ports:
      main:
        port: 8787
        protocol: tcp
        targetPort: 8787
  udpgameport:
    enabled: true
    ports:
      udpgameport:
        enabled: true
        port: 8787
        protocol: udp
        targetPort: 8787
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          GAME_ID: "1670340"
          GAME_PARAMS: ""
          VALIDATE: false
          USERNAME: ""
          PASSWRD: ""
