image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/mango
  tag: latest@sha256:c503c0cd9c485431bb80084b55a42546150f45fa703ad1de33ed5ff57bf06d5c
persistence:
  config:
    enabled: true
    mountPath: /root/.config/mango
  data:
    enabled: true
    mountPath: /root/mango
service:
  main:
    ports:
      main:
        port: 9000
        protocol: tcp
        targetPort: 9000
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
