image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/phpmyadmin
  tag: latest@sha256:732483189d167c9fd787dd9c6f090dec05aac5f8b8c81898ad4ae1494c9e888e
service:
  main:
    ports:
      main:
        port: 8080
        protocol: http
        targetPort: 80
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          MYSQL_PASSWORD: root
          MYSQL_USER: root
          PMA_HOST: 192.168.70.99
          PMA_PORT: "3306"
          # PMA_ABSOLUTE_URI: ""
