image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/pyload-ng
  tag: latest@sha256:aace9a9083840d076b4cfce91e2ebe6a3a2bf659bf8f40204271636973bf2d76
persistence:
  config:
    enabled: true
    mountPath: /config
  pathdownloads:
    enabled: true
    mountPath: /downloads
service:
  main:
    ports:
      main:
        port: 8000
        protocol: http
        targetPort: 8000
  port9666:
    enabled: true
    ports:
      port9666:
        enabled: true
        port: 9666
        protocol: tcp
        targetPort: 9666
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          UMASK: ""
