image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/chromium
  tag: latest@sha256:74939fe19daeca72c9b694919af6741656996990310132e17bf99a8ec9a7b284
persistence:
  datadir:
    enabled: true
    mountPath: /chrome
service:
  main:
    ports:
      main:
        port: 8080
        protocol: tcp
        targetPort: 8080
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          CUSTOM_RES_H: "768"
          CUSTOM_RES_W: "1280"
          EXTRA_PARAMETERS: ""
          UMASK: "000"
