image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/metatube
  tag: latest@sha256:70586a9bad50176b96c574fba85265caa1aadc911982304af77ef2966987793d
persistence:
  storagedatabase:
    enabled: true
    mountPath: /database
  storagedownloads:
    enabled: true
    mountPath: /downloads
service:
  main:
    ports:
      main:
        port: 5000
        protocol: tcp
        targetPort: 5000
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          DEBUG: "False"
          LOG: "False"
          LOG_LEVEL: "10"
          SOCKET_LOG: "False"
