image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/tasmobackup
  tag: latest@sha256:f191e4de7867b74936d33cbb4d02ddc21515a0bc9327c9544174d3e88e2c5768
persistence:
  data:
    enabled: true
    mountPath: /var/www/html/data
service:
  main:
    ports:
      main:
        port: 8259
        protocol: tcp
        targetPort: 80
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          DBNAME: data/tasmobackup
          DBTYPE: sqlite
