image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/obsidian
  tag: 0.1.1@sha256:d00f623e2de8a2bf78807d9aaeb25ee5d3f0f08e18c83afef49e71b5f389964f
service:
  main:
    ports:
      main:
        port: 10292
        protocol: http
        targetPort: 8080
  api:
    enabled: true
    ports:
      http:
        enabled: true
        port: 27123
        targetPort: 27123
      https:
        enabled: true
        port: 27124
        targetPort: 27124
persistence:
  storageconfig:
    enabled: true
    mountPath: /config/.config/obsidian
  storagevaults:
    enabled: true
    mountPath: /vaults
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
