image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/bitcoinunlimited
  tag: latest@sha256:142797786f3755fa11d7c0b9749ac62b3d8e8de5afd33bf567eba679738627a5
persistence:
  data:
    enabled: true
    mountPath: /data
service:
  communicationp:
    enabled: true
    ports:
      communicationp:
        enabled: true
        port: 8333
        protocol: tcp
        targetPort: 8333
  main:
    ports:
      main:
        port: 8332
        protocol: tcp
        targetPort: 8332
  testnetcommuni:
    enabled: true
    ports:
      testnetcommuni:
        enabled: true
        port: 18333
        protocol: tcp
        targetPort: 18333
  testnetrpcport:
    enabled: true
    ports:
      testnetrpcport:
        enabled: true
        port: 18332
        protocol: tcp
        targetPort: 18332
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
