image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/postscriptum
  tag: latest@sha256:62f2a0b95b1074b714a9948163ce951e9b3cdafe35f966c7e70eb7e0d425c1b7
service:
  main:
    ports:
      main:
        port: 10027
        protocol: udp
        targetPort: 10027
  queryport:
    enabled: true
    ports:
      queryport:
        enabled: true
        port: 10037
        protocol: udp
        targetPort: 10037
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env:
          DATA_PERM: "770"
          GAME_ID: "746200"
          GAME_PARAMS: Port=10027 QueryPort=10037 -log
          VALIDATE: false
          USERNAME: ""
          PASSWRD: ""
