image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/vaulthunters
  tag: latest@sha256:43972301c330485b1afaed4ec93b100f651f24f5ed1312c6026a8297649ede89
persistence:
  data:
    enabled: true
    mountPath: /data
service:
  main:
    ports:
      main:
        port: 25565
        protocol: tcp
        targetPort: 25565
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          EULA: "false"
          JVM_OPTS: -Xms6144m -Xmx8192m
          OPS: ""
