image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/memories-of-mars
  tag: latest@sha256:9dce6a699d82fca9dc4a44de393b060c606d22601469672e528b703239fa2697
service:
  main:
    ports:
      main:
        port: 7777
        protocol: udp
        targetPort: 7777
  beaconport:
    enabled: true
    ports:
      beaconport:
        enabled: true
        port: 15000
        protocol: udp
        targetPort: 15000
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env:
          GAME_ID: "897590"
          GAME_PARAMS: ""
          MULTIHOME: ""
          VALIDATE: false
          USERNAME: ""
          PASSWRD: ""
