image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/rust
  tag: latest@sha256:efe01c59101dd5b1bc760be9bb483733954bb95362b287483f44ed21d3b676ef
service:
  main:
    ports:
      main:
        port: 28015
        protocol: udp
        targetPort: 28015
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env:
          GAME_ID: "258550"
          GAME_PARAMS: +server.maxplayers 10
          GAME_PORT: "28015"
          OXIDE_MOD: ""
          SERVER_DISCRIPTION: Simple Unraid Rust Docker Server
          SERVER_NAME: RustDockerServer
          VALIDATE: false
          USERNAME: ""
          PASSWRD: ""
