image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/trango
  tag: latest@sha256:8d3c2dcd79a85a1907e5ca661983a3e19ef1d351ae2cfd8e96567a6175f9d9e3
persistence:
  config:
    enabled: true
    mountPath: /config
service:
  hostport2:
    enabled: true
    ports:
      hostport2:
        enabled: true
        port: 5533
        protocol: tcp
        targetPort: 443
  main:
    ports:
      main:
        port: 7755
        protocol: tcp
        targetPort: 80
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
