image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/v-rising
  tag: latest@sha256:2cd2d4a498d215598bcf353f6268f4e5f527cc0852c9a7028927628417c99757
service:
  main:
    ports:
      main:
        port: 9876
        protocol: udp
        targetPort: 9876
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env:
          ENABLE_BEPINEX: ""
          GAME_ID: "1829350"
          GAME_PARAMS: ""
          SERVER_NAME: V Rising Docker
          VALIDATE: false
          WORLD_NAME: world1
          USERNAME: ""
          PASSWRD: ""
