image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/nightscout
  tag: latest@sha256:03d918c83e70f2c9f42f8ba9a7cf08c6d6ec398c35fda6d719895ea59c4b17dc
persistence: {}
service:
  main:
    ports:
      main:
        port: 1337
        protocol: tcp
        targetPort: 1337
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          API_SECRET: ""
          BASE_URL: ""
          BG_HIGH: ""
          BG_LOW: ""
          BG_TARGET_BOTTOM: ""
          BG_TARGET_TOP: ""
          DISPLAY_UNITS: ""
          ENABLE: delta direction upbat timeago devicestatus errorcodes ar2 simplealarms profile
          INSECURE_USE_HTTP: "true"
          MONGO_CONNECTION: mongodb://db-user:db-password@mongodb-instance:port/db-name
          THEME: colors
          TIME_FORMAT: "24"
