image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/garrysmod
  tag: latest@sha256:272cc5260894da22d41dea0b8bd7fc3213011dce2974978830156d3771dfc046
service:
  main:
    ports:
      main:
        port: 27015
        protocol: udp
        targetPort: 27015
  tcprcon:
    enabled: true
    ports:
      tcprcon:
        enabled: true
        port: 27015
        protocol: tcp
        targetPort: 27015
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              port: "{{ .Values.service.tcprcon.ports.tcprcon.targetPort }}"
            readiness:
              port: "{{ .Values.service.tcprcon.ports.tcprcon.targetPort }}"
            startup:
              port: "{{ .Values.service.tcprcon.ports.tcprcon.targetPort }}"
        env:
          GAME_ID: "4020"
          GAME_NAME: garrysmod
          GAME_PARAMS: -secure +maxplayers 12 +map gm_flatgrass
          GAME_PORT: "27015"
          VALIDATE: false
          USERNAME: ""
          PASSWRD: ""
