image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/firefox-desktop-g3
  tag: latest@sha256:3d569138f38c907afa3f3a527bd00f64904287bc3028510511f0fcbc48b0f785
persistence:
  internalshare:
    enabled: true
    mountPath: /UNRAID_SHARE
service:
  main:
    ports:
      main:
        port: 6901
        protocol: http
        targetPort: 6901
  webuivnc:
    enabled: true
    ports:
      webuivnc:
        enabled: true
        port: 5901
        protocol: tcp
        targetPort: 5901
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          VNC_PW: unraid
          VNC_RESOLUTION: 1360x768
