image:
  repository: tccr.io/truecharts/sheetable
  tag: v0.8@sha256:fdeb1068aec5148f7f4ebe494981e3fccf179bf8e0bf9767fe786bf91ae9fce6
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10284
        protocol: http
persistence:
  config:
    enabled: true
    mountPath: "/app/config"
postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: sheetable
  postgresqlDatabase: sheetable
portal:
  open:
    enabled: true
securityContext:
  container: null
workload:
  main:
    podSpec:
      containers:
        env:
          PORT: "{{ .Values.service.main.ports.main.port }}"
          CONFIG_PATH: "/app/config/"
          DB_DRIVER: "postgres"
          DB_PORT: "5432"
          DB_NAME: "{{ .Values.cnpg.database }}"
          DB_USER: "{{ .Values.cnpg.user }}"
          DB_HOST:
            secretKeyRef:
              name: cnpg-main-urls
              key: plainhost
          DB_PASSWORD:
            secretKeyRef:
              name: cnpg-main-urls
              key: postgresql-password
          API_SECRET:
            secretKeyRef:
              name: sheetable-secrets
              key: API_SECRET
          ADMIN_EMAIL: "email@domain.com"
          ADMIN_PASSWORD: "changeme"
