image:
  repository: tccr.io/truecharts/fireflyiii-fidi
  pullPolicy: IfNotPresent
  tag: 0.9.16@sha256:53462b22258af5dabe98919f6c0c4ebaf7bc22c597ba840320fc208f13c3a745
service:
  main:
    ports:
      main:
        port: 10580
        protocol: http
        targetPort: 8080
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        env:
          # User Defined
          FIREFLY_III_URL: ""
          VANITY_URL: ""
          # User Defined
          FIREFLY_III_ACCESS_TOKEN: ""
          NORDIGEN_ID: ""
          NORDIGEN_KEY: ""
          SPECTRE_APP_ID: ""
          SPECTRE_SECRET: ""
