image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/survivethenights
  tag: latest@sha256:7571a30225c644e260418b5dde61d022371facccec2ca84fd14772833cca388d
service:
  main:
    ports:
      main:
        port: 7950
        protocol: udp
        targetPort: 7950
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env:
          DEBUG_OUTPUT: "false"
          GAME_ID: "1502300"
          GAME_PARAMS: ""
          VALIDATE: false
          USERNAME: ""
          PASSWRD: ""
