image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/ra-rom-processor
  tag: latest@sha256:9fe8d82fb90ba6bd4761ffb910ba490a542306db25c0b37a66a8d6b6c8d611c6
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
persistence:
  config:
    enabled: true
    mountPath: /config
  cache:
    enabled: true
    mountPath: /cache
  input:
    enabled: true
    mountPath: /input
  output:
    enabled: true
    mountPath: /output
  backup:
    enabled: true
    mountPath: /backup
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env:
          AquireRomSets: false
          AutoStart: false
          ConcurrentDownloadThreads: 1
          DeDupe: false
          EnableUnsupportedPlatforms: false
          ScrapeMetadata: false
          ScriptInterval: "1h"
          keepBackupsOfImportedRoms: true
          skyscraperLanguagePreference: "en"
          ScreenscraperPassword: ""
          ScreenscraperUsername: ""
