image:
  repository: tccr.io/truecharts/privatebin
  pullPolicy: IfNotPresent
  tag: 1.5.1@sha256:b6ea3267f06301b04c57409fe4deebb056c0552eff0ebff4b8f2cd91f0f98943
privatebin:
  # See also: https://github.com/PrivateBin/PrivateBin/wiki/Configuration
  main:
    name: ""
    basepath: ""
    discussion: true
    opendiscussion: false
    password: true
    fileupload: false
    burnafterreadingselected: false
    defaultformatter: "plaintext"
    syntaxhighlightingtheme: ""
    sizelimit: 10485760
    template: "bootstrap"
    info: ""
    notice: ""
    languageselection: false
    languagedefault: ""
    urlshortener: ""
    qrcode: ""
    icon: ""
    cspheader: ""
    zerobincompatibility: ""
    httpwarning: ""
    compression: ""
  expire:
    default: "1week"
  traffic:
    limit: 10
    exempted: ""
    creators: ""
    header: ""
  purge:
    limit: 300
    batchsize: 10
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8080
        port: 10248
persistence:
  run:
    enabled: true
    mountPath: "/run"
    type: "emptyDir"
    medium: "Memory"
  nginx-cache:
    enabled: true
    mountPath: "/var/lib/nginx/tmp"
    type: "emptyDir"
  conf-app:
    enabled: true
    type: "custom"
    readOnly: true
    mountPath: "/srv/cfg"
    volumeSpec:
      secret:
        secretName: '{{ include "tc.v1.common.names.fullname" . }}-secret'
  conf-php:
    enabled: true
    type: "custom"
    readOnly: true
    mountPath: "/etc/php8/conf.d/10-sizelimits.ini"
    subPath: "sizelimits-php.ini"
    volumeSpec:
      configMap:
        name: '{{ include "tc.v1.common.names.fullname" . }}-config'
  conf-nginx:
    enabled: true
    type: "custom"
    readOnly: true
    mountPath: "/etc/nginx/conf.d/sizelimits.conf"
    subPath: "sizelimits-nginx.conf"
    volumeSpec:
      configMap:
        name: '{{ include "tc.v1.common.names.fullname" . }}-config'
postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: privatebin
  postgresqlDatabase: privatebin
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsUser: 65534
    runAsGroup: 82
    fsGroup: 82
workload:
  main:
    podSpec:
      containers:
        env:
          TZ: "{{ .Values.TZ }}"
          PHP_TZ: "{{ .Values.TZ }}"
