image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/openttd
  tag: latest@sha256:f30676644961fad87b2675aab634a31e248869bc401dc30ef813553acee3c550
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
service:
  main:
    ports:
      main:
        port: 9015
        protocol: http
        targetPort: 8080
  tcpgameport:
    enabled: true
    ports:
      tcpgameport:
        enabled: true
        port: 3979
        protocol: tcp
        targetPort: 3979
  udpgameport:
    enabled: true
    ports:
      udpgameport:
        enabled: true
        port: 3979
        protocol: udp
        targetPort: 3979
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          GAME_PARAMS: ""
          GAME_VERSION: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
          GFX_PK_V: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
