image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/core-keeper-dedicated-server
  tag: latest@sha256:62731a8793f08ea7c9fea56f92cfe46888e1f7111d84f5c6bfd6be4ab85843a3
persistence:
  datafiles:
    enabled: true
    mountPath: /home/steam/core-keeper-data
  serverfiles:
    enabled: true
    mountPath: /home/steam/core-keeper-dedicated
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env:
          DATA_PATH: ""
          GAME_ID: examplegameidwillgohere
          MAX_PLAYERS: "10"
          WORLD_INDEX: "0"
          WORLD_NAME: World name here
