image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/goaccess-npm-logs
  tag: latest@sha256:dd994ed965f5f827e01ae63ec7d66d7cf9452e14ff05b678c7d4ba7dca701a34
persistence:
  hostpath1:
    enabled: true
    mountPath: /opt/log
    readOnly: true
service:
  main:
    ports:
      main:
        port: 7880
        protocol: tcp
        targetPort: 7880
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          BASIC_AUTH: "True"
          BASIC_AUTH_PASSWORD: x
          BASIC_AUTH_USERNAME: x
          DEBUG: "False"
          EXCLUDE_IPS: ""
          SKIP_ARCHIVED_LOGS: "False"
