image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/longvinter
  tag: latest@sha256:84ce057773a4e3894fad415d04e65a5daa85b8fd11208445db15d969fd6c9b19
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
service:
  main:
    ports:
      main:
        port: 27016
        protocol: udp
        targetPort: 27016
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env:
          GAME_PARAMS: ""
          GAME_PORT: "27016"
