image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/breitbandmessung-de
  tag: latest@sha256:ebc374b4fe484f479e7ffdd9d42d98b69ec6523052dc3ec353bb7c45e1e6a88e
persistence:
  config:
    enabled: true
    mountPath: /usr/src/app/config
  messurementlogs:
    enabled: true
    mountPath: /export/
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env: {}
