image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/tachidesk-docker
  tag: latest@sha256:3a19b630d9ca31cbc2f130c8fbedf2aa1b6aea1d62b1a47661b221e63311ae16
persistence:
  appdata:
    enabled: true
    mountPath: /home/suwayomi/.local/share/Tachidesk
  library:
    enabled: true
    mountPath: /home/suwayomi/.local/share/Tachidesk/downloads
  local-library:
    enabled: true
    mountPath: /home/suwayomi/.local/share/Tachidesk/local
service:
  main:
    ports:
      main:
        port: 4567
        protocol: tcp
        targetPort: 4567
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
