image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/arksurvivalevolved
  tag: latest@sha256:6c3c2c8ce43c350b88e93943eb99265499680011f2eb5b912652e226a19bd47c
ark:
  srv_admin_pass: ""
  srv_password: ""
  username: ""
  password: ""
  game_id: "376030"
  rcon_enabled: true
  game_params: []
  game_params_extra: []
  easy_game_extra_params:
    server: true
    log: true
    crossplay: true
  map: TheIsland
  # Used only for SCALE GUI
  custom_map: ""
  server_name: ""
  validate: false
service:
  main:
    ports:
      main:
        port: 7777
        protocol: udp
  udp2:
    enabled: true
    ports:
      udp2:
        enabled: true
        # This should always be main +1
        port: 7778
        protocol: udp
  udpsteam:
    enabled: true
    ports:
      udpsteam:
        enabled: true
        port: 27015
        protocol: udp
  rcontcp:
    enabled: true
    ports:
      rcontcp:
        enabled: true
        port: 27020
        protocol: tcp
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              port: "{{ .Values.service.rcontcp.ports.rcontcp.port }}"
            readiness:
              port: "{{ .Values.service.rcontcp.ports.rcontcp.port }}"
            startup:
              port: "{{ .Values.service.rcontcp.ports.rcontcp.port }}"
          envFrom:
            - secretRef:
                name: '{{ include "tc.v1.common.names.fullname" . }}-secret'
