image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/btdex
  tag: latest@sha256:a96f96ce9cbcb880cf9f6380d5bf5a289e8e4955eb5ab719b897200fb3b47fe7
persistence:
  btdex:
    enabled: true
    mountPath: /opt/btdex/cache
service:
  main:
    ports:
      main:
        port: 5800
        protocol: tcp
        targetPort: 8080
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          DISPLAY_HEIGHT: 800|900|1050
          DISPLAY_WIDTH: 1440|1680
