image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/fireshare
  tag: 1.2.8@sha256:9a8893666987d6a2a0ee18281ef55632630d3eee904886194372f9fe2961c068
service:
  main:
    ports:
      main:
        port: 10287
        protocol: http
        targetPort: 80
persistence:
  data:
    enabled: true
    mountPath: /data
  processeddata:
    enabled: true
    mountPath: /processed
  videos:
    enabled: true
    mountPath: /videos
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          SECRET_KEY:
            secretKeyRef:
              name: fireshare-secrets
              key: SECRET_KEY
          MINUTES_BETWEEN_VIDEO_SCANS: 5
          ADMIN_PASSWORD: "changeme"
