image:
  pullPolicy: IfNotPresent
  repository: splunk/splunk
  tag: 9.0.4@sha256:864f89b8acee4d54c81f9431da78175ff70379d554ab3f3db3d2c92fb4641b8d
splunk:
  acceptLicense: true
  password: changeme
  extraArgs: []
service:
  dataingest:
    enabled: true
    ports:
      dataingest:
        enabled: true
        port: 9997
        protocol: http
        targetPort: 9997
  main:
    ports:
      main:
        port: 8000
        protocol: http
        targetPort: 8000
  management:
    enabled: true
    ports:
      management:
        enabled: true
        port: 8089
        protocol: http
        targetPort: 8089
persistence:
  appcreds:
    enabled: true
    mountPath: /opt/splunk/etc/
  config:
    enabled: true
    mountPath: /opt/splunk/var
  datap:
    enabled: true
    mountPath: /splunkdata
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          envFrom:
            - secretRef:
                name: '{{ include "tc.v1.common.names.fullname" . }}-splunk-config'
