image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/tubearchivist-redisjson
  tag: latest@sha256:db9d04bbf52e3707e70fc44bab1a0ec69fe6eaebfbbabf6bdc3069de7f71efba
persistence:
  data:
    enabled: true
    mountPath: /data
service:
  main:
    ports:
      main:
        port: 6379
        protocol: tcp
        targetPort: 6379
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
