image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/left4dead
  tag: latest@sha256:a098c232ea6e316ef2f24cab28c095101fa79d1fa7bb989bb955ed6c77b18f59
service:
  main:
    ports:
      main:
        port: 27015
        protocol: udp
        targetPort: 27015
  tcprcon:
    enabled: true
    ports:
      tcprcon:
        enabled: true
        port: 27015
        protocol: tcp
        targetPort: 27015
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              port: "{{ .Values.service.tcprcon.ports.tcprcon.targetPort }}"
            readiness:
              port: "{{ .Values.service.tcprcon.ports.tcprcon.targetPort }}"
            startup:
              port: "{{ .Values.service.tcprcon.ports.tcprcon.targetPort }}"
        env:
          GAME_ID: "222840"
          GAME_NAME: left4dead
          GAME_PARAMS: +maxplayers 4 +map l4d_farm04_barn
          GAME_PORT: "27015"
          VALIDATE: false
          USERNAME: ""
          PASSWRD: ""
