image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/barotrauma
  tag: latest@sha256:29c3e533bff810305d61fd7bce5b20782c5224241d4993878334fba5ee355e82
service:
  main:
    ports:
      main:
        port: 27015
        protocol: udp
        targetPort: 27015
  steamqueryport:
    enabled: true
    ports:
      steamqueryport:
        enabled: true
        port: 27016
        protocol: udp
        targetPort: 27016
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env:
          GAME_ID: "1026340"
          GAME_PARAMS: ""
          VALIDATE: false
          USERNAME: ""
          PASSWRD: ""
