image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/notarius
  tag: latest@sha256:dfda981ce2e5b84208b431ffe4390af5797ad3f9e1117939f1a0f56fd713439f
persistence: {}
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env: {}
