image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/americasarmy-pg
  tag: latest@sha256:8475bc1cf676555fa5567c833667e9015c4d0d2c35c76f225064026fabe96b9e
service:
  main:
    ports:
      main:
        port: 8778
        protocol: udp
        targetPort: 8778
  steamqueryport:
    enabled: true
    ports:
      steamqueryport:
        enabled: true
        port: 27015
        protocol: udp
        targetPort: 27015
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env:
          GAME_ID: "203300"
          GAME_PARAMS: -port=7778 -SAP=8778 -SQP=27015 -aauregion=1 -log=Server.log
          SRV_NAME: Army Docker
          VALIDATE: false
          USERNAME: ""
          PASSWRD: ""
