image:
  repository: tccr.io/truecharts/bender
  tag: v1.0.3@sha256:28728f8b8d485c295ab19e96e6f90df111f6e0aa048b7d679222c63e4bf759b5
  pullPolicy: IfNotPresent
bender:
  init_assets: true
service:
  main:
    ports:
      main:
        port: 10353
        protocol: http
        targetPort: 8080
persistence:
  config:
    enabled: true
    mountPath: /app/static
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        env:
          INIT_ASSETS: '{{ ternary "1" "0" .Values.bender.init_assets }}'
