image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/hoobs
  tag: latest@sha256:64224ac21a14adb8f937237cb7979445581ccfa900c19ead377c60d38a0a2b3c
persistence:
  applicationpath:
    enabled: true
    mountPath: /hoobs
service:
  homebridgeport:
    enabled: true
    ports:
      homebridgeport:
        enabled: true
        port: 51826
        protocol: tcp
        targetPort: 51826
  main:
    ports:
      main:
        port: 8082
        protocol: http
        targetPort: 80
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
