image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/ts-dnsserver
  tag: latest@sha256:a0d40a6c7c414c4af4f7a6e8b087fdda7069d16c1ba8c6eb7407ca21541c2829
persistence:
  config:
    enabled: true
    mountPath: /config
service:
  dnsport:
    enabled: true
    ports:
      dnsport:
        enabled: true
        port: 53
        protocol: udp
        targetPort: 53
  main:
    ports:
      main:
        port: 5380
        protocol: http
        targetPort: 5380
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
