image:
  repository: tccr.io/truecharts/upsnap
  pullPolicy: IfNotPresent
  tag: 3.0.6@sha256:7d116a07c590535dcd4390ad73dc469e6f0b1aefb67241e7ac1ab140943e7f7a
hostNetwork: true
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8090
        port: 10611
persistence:
  data:
    enabled: true
    mountPath: /app/pb_data
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        env:
          UPSNAP_INTERVAL: "@every 10s"
          UPSNAP_SCAN_RANGE: 192.168.1.0/24
          UPSNAP_WEBSITE_TITLE: Truecharts WOL
