image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/insurgencysandstorm
  tag: latest@sha256:aa9fe6535aa5f745e74c3b6a1eaf31624fc5fa4d392bce3814325dd3383be813
service:
  main:
    ports:
      main:
        port: 27102
        protocol: udp
        targetPort: 27102
  queryport:
    enabled: true
    ports:
      queryport:
        enabled: true
        port: 27131
        protocol: udp
        targetPort: 27131
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env:
          GAME_ID: "581330"
          GAME_PARAMS: Oilfield?Scenario=Scenario_Refinery_Push_Security?MaxPlayers=28?Password=Docker
          GAME_PORT: "27102"
          QUERY_PORT: "27131"
          SERVER_NAME: DockerServer
          VALIDATE: false
          USERNAME: ""
          PASSWRD: ""
