image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/backuppc
  tag: latest@sha256:34ba1848b1daca5a0857f4831c76b834ebec94e98717f415b2db835421fdcd0b
persistence:
  backuplocation:
    enabled: true
    mountPath: /var/lib/backuppc
  configurationfiles:
    enabled: true
    mountPath: /etc/backuppc
  homedirectory:
    enabled: true
    mountPath: /home/backuppc
  logs:
    enabled: true
    mountPath: /www/logs
service:
  main:
    ports:
      main:
        port: 8000
        protocol: tcp
        targetPort: 80
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
