image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/alienswarm
  tag: latest@sha256:297a2344be4f8f3a150e1d1b22f8b160af45a0f3f577f211d7849fb5cd76be48
service:
  main:
    ports:
      main:
        port: 27015
        protocol: udp
        targetPort: 27015
  tcprconport:
    enabled: true
    ports:
      tcprconport:
        enabled: true
        port: 27015
        protocol: tcp
        targetPort: 27015
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              port: "{{ .Values.service.tcprconport.ports.tcprconport.targetPort }}"
            readiness:
              port: "{{ .Values.service.tcprconport.ports.tcprconport.targetPort }}"
            startup:
              port: "{{ .Values.service.tcprconport.ports.tcprconport.targetPort }}"
        env:
          GAME_ID: "635"
          GAME_NAME: swarm
          GAME_PARAMS: +map lobby -maxplayers 4 +exec server.cfg
          GAME_PORT: "27015"
          VALIDATE: false
          USERNAME: ""
          PASSWRD: ""
