image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/pixark
  tag: latest@sha256:5f926d67bdf54adcd255ec0d04e561a108c04ff1574ff6e2c3a65e7877777540
service:
  main:
    ports:
      main:
        port: 27015
        protocol: udp
        targetPort: 27015
  cubeport:
    enabled: true
    ports:
      cubeport:
        enabled: true
        port: 27018
        protocol: udp
        targetPort: 27018
  queryport:
    enabled: true
    ports:
      queryport:
        enabled: true
        port: 27016
        protocol: udp
        targetPort: 27016
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env:
          GAME_ID: "824360"
          GAME_PARAMS: ?MaxPlayers=10
          GAME_PARAMS_EXTRA: -QueryPort=27016 -Port=27015 -CubePort=27018 -NoBattlEye -nosteamclient -game -server -log
          MAP: CubeWorld_Light
          SERVER_NAME: PIXARKDocker
          SRV_ADMIN_PWD: adminDocker
          SRV_PWD: Docker
          VALIDATE: false
          USERNAME: ""
          PASSWRD: ""
