image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/pwm
  tag: latest@sha256:5c27b39dff4004a40a5b7b71d25361efec2b669e367923dc43fa582d614ba4ba
persistence:
  appdata:
    enabled: true
    mountPath: /usr/share/pwm
service:
  main:
    ports:
      main:
        port: 8282
        protocol: tcp
        targetPort: 8080
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          PWM_APPLICATIONFLAGS: NoFileLock
