image:
  repository: tccr.io/truecharts/muse
  pullPolicy: IfNotPresent
  tag: 2.2.0@sha256:f4559eaaccab9d2cbc26190d4478d0bb091954c7c4217dbfc9de7489e860bdba
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: false
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        env:
          DATA_DIR: /config
          DISCORD_TOKEN: ""
          SPOTIFY_CLIENT_ID: ""
          SPOTIFY_CLIENT_SECRET: ""
          YOUTUBE_API_KEY: ""
          # CACHE_LIMIT: 2GB
          # BOT_STATUS: online
          # BOT_ACTIVITY_TYPE: PLAYING
          # BOT_ACTIVITY: A incubator app
          # BOT_ACTIVITY_URL: https://www.youtube.com/truecharts
