image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/hurtworld
  tag: latest@sha256:8cd614ff342c29345da12f2b3a75e5bc6a60ef0b6965cd0599a782a08deee80f
service:
  main:
    ports:
      main:
        port: 12871
        protocol: udp
        targetPort: 12871
  queryport:
    enabled: true
    ports:
      queryport:
        enabled: true
        port: 12881
        protocol: udp
        targetPort: 12881
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env:
          GAME_ID: "405100"
          GAME_PARAMS: ;autosaveenabled 1;addadmin 76561197963117432
          GAME_PORT: "12871"
          QUERY_PORT: "12881"
          SRV_MAXPLAYERS: "50"
          SRV_NAME: Hurtworld Docker
          VALIDATE: false
          USERNAME: ""
          PASSWRD: ""
