image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/fluttercoin-wallet
  tag: latest@sha256:c52984c78d52ee0ee450f549cb4e167170675d49fa6b4b8b1deaf733ec854bf6
persistence:
  datapath:
    enabled: true
    mountPath: /fluttercoin
service:
  jsonremoteport:
    enabled: true
    ports:
      jsonremoteport:
        enabled: true
        port: 7474
        protocol: tcp
        targetPort: 7474
  main:
    ports:
      main:
        port: 8080
        protocol: http
        targetPort: 8080
  peertopeerconn:
    enabled: true
    ports:
      peertopeerconn:
        enabled: true
        port: 7408
        protocol: tcp
        targetPort: 7408
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          CUSTOM_RES_H: "768"
          CUSTOM_RES_W: "1024"
          DATA_PERM: "770"
          EXTRA_PARAMS: -bind=0.0.0.0
          UMASK: "000"
