image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/alienswarm-reactivedrop
  tag: latest@sha256:6ca07d264bd1150d23af7148b98862b42d31384622aaca36e5937e7d4e9cc253
service:
  main:
    ports:
      main:
        port: 27015
        protocol: udp
        targetPort: 27015
  tcprconport:
    enabled: true
    ports:
      tcprconport:
        enabled: true
        port: 27015
        protocol: tcp
        targetPort: 27015
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              port: "{{ .Values.service.tcprconport.ports.tcprconport.targetPort }}"
            readiness:
              port: "{{ .Values.service.tcprconport.ports.tcprconport.targetPort }}"
            startup:
              port: "{{ .Values.service.tcprconport.ports.tcprconport.targetPort }}"
        env:
          GAME_ID: "563560"
          GAME_NAME: reactivedrop
          GAME_PARAMS: +map lobby -maxplayers 4 +exec server.cfg
          GAME_PORT: "27015"
          VALIDATE: false
          USERNAME: ""
          PASSWRD: ""
