image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/llalon-github-backup
  tag: latest@sha256:5dd9378be0f2354d85d22d19d71c28abd63f27eac6b829e03e58c7aa4d426c63
persistence:
  backuplocation:
    enabled: true
    mountPath: /home/docker/backups
  config:
    enabled: true
    mountPath: /home/docker/github-backup/config/
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env:
          SCHEDULE: "3600"
          TOKEN: 1a2b3c4d5e6f71a2b3c4d5e6f71a2b3c4d5e6f7b
