image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/guide2go
  tag: latest@sha256:123b847b8c3c12d89f434df91c44584e8367b1df26784439a681b08046257bf5
persistence:
  config:
    enabled: true
    mountPath: /config
  guide2go:
    enabled: true
    mountPath: /guide2go
  tvh:
    enabled: true
    mountPath: /TVH
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env: {}
