image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/searx
  tag: latest@sha256:71fce6b8ff15bcd79f1194281cfc4f8394b23596b962503cc9b6d1542ccfb88b
service:
  main:
    ports:
      main:
        port: 8080
        protocol: tcp
        targetPort: 8080
persistence:
  config:
    enabled: true
    mountPath: /etc/searx
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          BASE_URL: ""
