image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/chronograf
  tag: latest@sha256:2ffaf21a11a060bdace6973aae77cc5e0e94ff3609ab306e2c77affcc68dd076
persistence:
  chronograf:
    enabled: true
    mountPath: /var/lib/chronograf
service:
  main:
    ports:
      main:
        port: 8888
        protocol: tcp
        targetPort: 8888
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
