image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/shadowsocks
  tag: latest@sha256:9ea9e3daa9350fc8ed43c9fcc6d5c617f09ea6a292a6e66958a1f4d858926a9a
persistence: {}
service:
  main:
    ports:
      main:
        port: 8388
        protocol: tcp
        targetPort: 8388
  portudp:
    enabled: true
    ports:
      portudp:
        enabled: true
        port: 8388
        protocol: udp
        targetPort: 8388
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          DNS_ADDRS: 8.8.8.8,8.8.4.4
          METHOD: chacha20-ietf-poly1305
          PASSWORD: ""
          TIMEOUT: "300"
