image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/apprise-api
  tag: 1.2.0@sha256:5cf484c5d1689dcea1f28b8b089508150e122abf3bd8ee90131a03d68a4c95ca
service:
  main:
    ports:
      main:
        port: 8000
        protocol: http
        targetPort: 8000
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: False
    # runAsNonRoot: false

    runAsGroup: 33
    runAsUser: 33
    fsGroup: 33
workload:
  main:
    podSpec:
      containers:
        env:
          APPRISE_CONFIG_DIR: /config
          APPRISE_STATEFUL_MODE: hash
          APPRISE_DENY_SERVICES: windows,dbus,gnome,macos,syslog
          LOG_LEVEL: INFO
          DEBUG: "no"
          APPRISE_RECURSION_MAX: 1
          APPRISE_CONFIG_LOCK: no
          APPRISE_ALLOW_SERVICES: ""
          ALLOWED_HOSTS: "*"
          # APPRISE_STATELESS_URLS

          SECRET_KEY: "abc123"
