image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/debian-apt-mirror
  tag: latest@sha256:9fd27bc6e903fa2319111a441cabc0d4cbaeaa06d3d8aa43da21671c3cfc2e15
persistence:
  config:
    enabled: true
    mountPath: /debian-mirror/config
  data:
    enabled: true
    mountPath: /debian-mirror/data
service:
  main:
    ports:
      main:
        port: 980
        protocol: tcp
        targetPort: 980
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          APACHE2_PORT: "980"
          DATA_PERM: "770"
          FORCE_UPDATE: "false"
          UMASK: "0000"
