image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/kerbalspaceprogram-lmp
  tag: latest@sha256:66dcba56cd99b689332786bdeb50171bd5130e46a2df74f214841388644456b5
persistence:
  serverfiles:
    enabled: true
    mountPath: /lunamultiplayer
service:
  main:
    ports:
      main:
        port: 8800
        protocol: udp
        targetPort: 8800
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env:
          DATA_PERM: "770"
          LMP_V: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
          UMASK: "0000"
