image:
  repository: tccr.io/truecharts/fancyindex
  pullPolicy: IfNotPresent
  tag: latest@sha256:d6452b6329c3313304db78ec1d7ba82b94c197f7a544a5353e7401dc3da041e4
service:
  main:
    ports:
      main:
        port: 10235
        targetPort: 80
persistence:
  share:
    enabled: true
    mountPath: "/share"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        env:
          CONTAINER_TIMEZONE: "{{ .Values.TZ }}"
          # User Defined
          DISABLE_AUTH: false
          SET_CONTAINER_TIMEZONE: true
          WEBUSER: "webuser"
          WEBPASSWORD: "webpassword"
