image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/go-auto-yt
  tag: vstable@sha256:4d09813e06a3e27ec206d39434c7f05457812c5728aac668f5fffc2ca48c63f3
persistence:
  config:
    enabled: true
    mountPath: /app/config
  mounteddownloadsfolder:
    enabled: true
    mountPath: /app/downloads
service:
  main:
    ports:
      main:
        port: 9000
        protocol: tcp
        targetPort: 8080
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          UMASK_SET: "0022"
