image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/avorion
  tag: latest@sha256:d9e30669f6e5ed8bd890d158043bab0c3569265ca0952125a939a625d1ae0123
stdin: true
tty: true
service:
  main:
    ports:
      main:
        port: 27000
        protocol: tcp
        targetPort: 27000
  hostport2:
    enabled: true
    ports:
      hostport2:
        enabled: true
        port: 27000
        protocol: udp
        targetPort: 27000
  hostport3:
    enabled: true
    ports:
      hostport3:
        enabled: true
        port: 27003
        protocol: udp
        targetPort: 27003
  hostport4:
    enabled: true
    ports:
      hostport4:
        enabled: true
        port: 27020
        protocol: udp
        targetPort: 27020
  hostport5:
    enabled: true
    ports:
      hostport5:
        enabled: true
        port: 27021
        protocol: udp
        targetPort: 27021
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env:
          GALAXY_NAME: AvorionDocker
          GAME_ID: "565060"
          GAME_PARAMS: ""
          VALIDATE: false
          USERNAME: ""
          PASSWRD: ""
