image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/mediaelch
  tag: latest@sha256:e2b3f2f9e9d8307078ff394f9fce0be4279a7dfdc36c7f2612d539839f1d8915
persistence:
  mediaelch:
    enabled: true
    mountPath: /shows
service:
  main:
    ports:
      main:
        port: 5800
        protocol: tcp
        targetPort: 5800
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          UMASK: "000"
