image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/photostructure
  tag: vstable@sha256:60d2f7530872c7b65a126221e59d16e356e269dce2ca68a3c3f4f0c3f46ff3bf
persistence:
  config:
    enabled: true
    mountPath: /ps/config
  library:
    enabled: true
    mountPath: /ps/library
  logs:
    enabled: true
    mountPath: /ps/logs
  tempscratchdisk:
    enabled: true
    mountPath: /ps/tmp
service:
  main:
    ports:
      main:
        port: 1787
        protocol: tcp
        targetPort: 1787
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          PS_LOG_LEVEL: ""
          UMASK: ""
