image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/cadquery-jupyter
  tag: 3.4.0@sha256:1fad7b53f0b220282b478e70ef2a41e13a886cb4330de17fcab53c56fc29318b
persistence:
  workdir:
    enabled: true
    mountPath: /home/cq
service:
  main:
    ports:
      main:
        port: 8888
        protocol: tcp
        targetPort: 8888
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
