image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/namecheap-ddns
  tag: latest@sha256:fcb0cacda3094eeca539289014d115207e005d2beefb279b31c07351d006d79a
persistence: {}
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env:
          APP_DOMAIN: ""
          APP_HOST: ""
          APP_PASSWORD: ""
