image:
  repository: tccr.io/truecharts/magicmirror-2
  pullPolicy: IfNotPresent
  tag: latest@sha256:d39dd5ba0f16b97ce6da85803c780fa6880569dbcce141c6a4e4700079501625
magicmirror:
  force_update: false
  force_update_modules: false
service:
  main:
    ports:
      main:
        port: 10590
        protocol: http
        targetPort: 10000
persistence:
  config:
    enabled: true
    mountPath: /magicmirror2
  # Mounts a modified default config file to a "tmp" which the entrypoint,
  # copies to the config location if it does not exist.
  configfile:
    enabled: true
    type: configMap
    mountPath: /tmp/config.js
    subPath: config.js
    objectName: '{{ printf "%s-magicmirror-config" (include "tc.v1.common.names.fullname" .) }}'
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: HTTP
              path: /
            readiness:
              type: HTTP
              path: /
            startup:
              type: HTTP
              path: /
          envFrom:
            - configMapRef:
                name: '{{ include "tc.v1.common.names.fullname" . }}-magicmirror-env'
