image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/seedsync
  tag: latest@sha256:e8e69dcebd7cd9b15af6484736e6d51df49d0e2757e067b1fe8b9b820c6780d1
persistence:
  config:
    enabled: true
    mountPath: /config
  downloads:
    enabled: true
    mountPath: /downloads
service:
  main:
    ports:
      main:
        port: 8800
        protocol: tcp
        targetPort: 8800
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
