image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/multi-scrobbler
  tag: latest@sha256:ce27d22bc4f5d03495cda386ee1be40ac160a542ac95c4fe5a83a68785f8beb8
persistence:
  config:
    enabled: true
    mountPath: /home/node/config
  logs:
    enabled: true
    mountPath: /home/node/app/logs
service:
  main:
    ports:
      main:
        port: 9078
        protocol: tcp
        targetPort: 9078
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
