image:
  repository: minio/minio
  tag: RELEASE.2024-03-15T01-07-19Z@sha256:ea2c70cda70860c7d10f04ce1df640d3abb995784cb7aeedef8d4baa53a5a113
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10107
        targetPort: 10107
  api:
    enabled: true
    ports:
      api:
        enabled: true
        targetPort: 10106
        port: 10106
ingress:
  api:
    targetSelector:
      api: api
persistence:
  config:
    enabled: true
    mountPath: "/data"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              custom: true
              spec:
                httpGet:
                  scheme: HTTP
                  path: "/minio/health/live"
                  port: 10106
            readiness:
              custom: true
              spec:
                httpGet:
                  scheme: HTTP
                  path: "/minio/health/ready"
                  port: 10106
          args:
            - "server"
            - "/data"
            - "--address"
            - ":10106"
            - "--console-address"
            - ":10107"
          env:
            MINIO_ROOT_USER: "minio"
            MINIO_BROWSER_REDIRECT_URL: ""
            MINIO_SERVER_URL: ""
            MINIO_ROOT_PASSWORD: "changeme"
