image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/glauth
  tag: latest@sha256:6447de431d0d9ffcd490a555a90cc3c00a315af6d579e160bd9e19ce82a5fd5f
persistence:
  config:
    enabled: true
    mountPath: /app/config
service:
  ldapport:
    enabled: true
    ports:
      ldapport:
        enabled: true
        port: 389
        protocol: tcp
        targetPort: 389
  ldapsport:
    enabled: true
    ports:
      ldapsport:
        enabled: true
        port: 636
        protocol: tcp
        targetPort: 636
  main:
    ports:
      main:
        port: 5555
        protocol: http
        targetPort: 5555
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
