image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/yacy
  tag: latest@sha256:5c7a68c3af87604e8404231147ed3fabf190226c9f4012d3653ea4d7135c9a35
persistence:
  appdata:
    enabled: true
    mountPath: /opt/yacy_search_server/DATA
service:
  https:
    enabled: true
    ports:
      https:
        enabled: true
        port: 8443
        protocol: tcp
        targetPort: 8443
  main:
    ports:
      main:
        port: 8090
        protocol: http
        targetPort: 8090
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
