image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/tanoshi
  tag: latest@sha256:8e471c679e5319c0d9d9bf25f5eaa4a470ca979a73ffa36e7ae295ad4f4edea3
persistence:
  directoryconfig:
    enabled: true
    mountPath: /tanoshi
service:
  main:
    ports:
      main:
        port: 80
        protocol: tcp
        targetPort: 80
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
