image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/fmd2-wine
  tag: latest@sha256:8fe3b964a8b93a5972a42a44ad47e3a92bb8f826570ee3acbacddc14d83ba772
persistence:
  appluamodulespath:
    enabled: true
    mountPath: /app/FMD2/lua
  appuserdata:
    enabled: true
    mountPath: /app/FMD2/userdata
  appwineconfig:
    enabled: true
    mountPath: /config/.wine
  data:
    enabled: true
    mountPath: /app/FMD2/data
  downloaddirectory:
    enabled: true
    mountPath: /downloads
service:
  main:
    ports:
      main:
        port: 6080
        protocol: tcp
        targetPort: 6080
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          UMASK: "002"
