image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/barcodebuddy
  tag: latest@sha256:c017d0776dd03aa15103289ff4268ae73512056d3fc083ef4aad0ffee32b10f9
persistence:
  config:
    enabled: true
    mountPath: /config
service:
  main:
    ports:
      main:
        port: 8450
        protocol: tcp
        targetPort: 80
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
