image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/artifactory-oss
  tag: 7.49.8@sha256:03fd99349f355b76fb956308c0b1066816b7f55661985ddc10e0886ef096f255
persistence:
  varoptjfrogartifactory:
    enabled: true
    mountPath: /var/opt/jfrog/artifactory
service:
  main:
    ports:
      main:
        port: 8181
        protocol: tcp
        targetPort: 8081
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          EXTRA_JAVA_OPTIONS: -Xms512m -Xmx4g
