image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/scprime
  tag: latest@sha256:6d1900c25c49294fede758967a61fbde5d5cfb01f68d558047397646a75b51d4
persistence:
  metadata:
    enabled: true
    mountPath: /scp-data
  storage:
    enabled: true
    mountPath: /storage
service:
  hostapiaddress:
    enabled: true
    ports:
      hostapiaddress:
        enabled: true
        port: 4283
        protocol: tcp
        targetPort: 4283
  main:
    ports:
      main:
        port: 4282
        protocol: tcp
        targetPort: 4282
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          SCPRIME_WALLET_PASSWORD: ""
