image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/pure-ftpd
  tag: latest@sha256:b54f029edd47df49e7af29ea5cf259467328b0495fceb3ae5f274224a34a9812
persistence:
  data:
    enabled: true
    mountPath: /data
  ftpfolder:
    enabled: true
    mountPath: /home
service:
  main:
    ports:
      main:
        port: 2100
        protocol: http
        targetPort: 2100
  pasvportrange:
    enabled: true
    ports:
      pasvportrange:
        enabled: true
        port: 30000
        protocol: tcp
        targetPort: 30000
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          AUTH_METHOD: puredb
          PASSIVE_PORT_RANGE: 30000:30009
          SECURE_MODE: "true"
