image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/terraria-tshock
  tag: vtshock@sha256:93dc07c1fbae51e58d02c678aa005b9c2820993255f2f4e4bee3565ebd26f23d
terraria:
  pass: secretpass
  autocreate: "1"
  seed: AwesomeSeed
  worldname: scale terraria
  maxplayers: 16
  lang: en-US
  easy_game_params:
    noupnp: true
    steam: false
    secure: false
  game_params: []
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
service:
  main:
    ports:
      main:
        port: 9014
        protocol: http
        targetPort: 8080
  tcp:
    enabled: true
    ports:
      tcp:
        enabled: true
        port: 7777
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          envFrom:
            - secretRef:
                name: '{{ include "tc.v1.common.names.fullname" . }}-secret'
