image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/pt-helper
  tag: latest@sha256:863b9b68ced867903093dd18ee69f9623229d279e68a3bc7ecd04c1e5c0871a3
persistence:
  data:
    enabled: true
    mountPath: /data
service:
  main:
    ports:
      main:
        port: 8192
        protocol: tcp
        targetPort: 8192
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
