image:
  repository: tccr.io/truecharts/cups-server
  tag: latest@sha256:3693f563728bbbd0fe155fda2245461cc1eeaee4d0703bc570f8815b1eceeb06
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 631
        targetPort: 631
persistence:
  config:
    enabled: true
    mountPath: "/etc/cups"
  dbus:
    enabled: true
    type: hostPath
    hostPath: "/var/run/dbus"
    mountPath: "/var/run/dbus"
    readOnly: false
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        env:
          ADMIN_PASSWORD: "secretpass"
