env:
  GAME_ID: "1169370"
  GAME_PARAMS: ""
  WORLD_NAME: World
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/necesse
  tag: latest@sha256:8d9cc50bddc601196c0f1efa9684314ca8fdc78877146dc5badf5bc8c8e41592
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 9023
        protocol: http
        targetPort: 8080
  udpgameport:
    enabled: true
    ports:
      udpgameport:
        enabled: true
        port: 14159
        protocol: udp
        targetPort: 14159

portal:
  open:
    enabled: true
