image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/tar1090
  tag: latest@sha256:391b130da0ace1896e10f1f1f08fe8433b2827479b85fe22f39bdad934f7ad72
persistence: {}
service:
  main:
    ports:
      main:
        port: 8078
        protocol: tcp
        targetPort: 80
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          BEASTHOST: <BEASTHOST>
          LAT: xx.xxxxx
          LONG: xx.xxxxx
          MLATHOST: <MLATHOST>
