image:
  repository: tccr.io/truecharts/briefkasten
  pullPolicy: IfNotPresent
  tag: latest@sha256:9f9e7ec82b607e7ee837065b84ce55beb756c54b99b7f96b8b62f71806fd50c6
briefkasten:
  general:
    nextauth_url: http://localhost:3000
  github:
    id: ""
    secret: ""
  google:
    id: ""
    secret: ""
  supabase:
    key:
    url:
    bucket_id:
  mail:
    from:
    server:
service:
  main:
    ports:
      main:
        port: 10349
        protocol: http
        targetPort: 3000
postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: briefkasten
  postgresqlDatabase: briefkasten
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
              type: HTTP
              path: /
            readiness:
              enabled: false
              type: HTTP
              path: /
            startup:
              enabled: false
              type: HTTP
              path: /
          envFrom:
            - secretRef:
                name: '{{ include "tc.v1.common.names.fullname" . }}-secret'
            - configMapRef:
                name: '{{ include "tc.v1.common.names.fullname" . }}-config'
