image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/hastebin
  tag: latest@sha256:c96d31472f9e6d354b2f54f8b96975ccf43ed1ff7aa0cc04984040f55c71dd0d
persistence:
  data:
    enabled: true
    mountPath: /app/data
service:
  main:
    ports:
      main:
        port: 7777
        protocol: tcp
        targetPort: 7777
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
