image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/mediagoblin
  tag: latest@sha256:5e5ab6e7c104861025014ff5b45c0b819b20d04ce097b160078da824b6fd8e02
persistence:
  appdata:
    enabled: true
    mountPath: /var/lib/mediagoblin
service:
  main:
    ports:
      main:
        port: 6543
        protocol: tcp
        targetPort: 6543
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
