image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/bitcoinwalletgui
  tag: latest@sha256:738088fa67f95e40f3fe46a4355079984e3560f78fb9ce7f583f01ace686f9dc
persistence:
  bitcoinblockchainpath:
    enabled: true
    mountPath: /headless/.bitcoin/
service:
  main:
    ports:
      main:
        port: 6901
        protocol: http
        targetPort: 6901
  vncport:
    enabled: true
    ports:
      vncport:
        enabled: true
        port: 5905
        protocol: tcp
        targetPort: 5901
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          VNC_PW: vncpassword
          VNC_RESOLUTION: 1280x1024
          VNC_VIEW_ONLY: "false"
