image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/filestash
  tag: latest@sha256:c458467b8cb89d3d4056da3657b0ca025283c486e5969f5aa864e3d1f9c1904b
persistence:
  appdata:
    enabled: true
    mountPath: /app/data/state/
service:
  main:
    ports:
      main:
        port: 8334
        protocol: tcp
        targetPort: 8334
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
