image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/citadel-forgedwithfire
  tag: latest@sha256:83ce718ca47d76d8b4887fc8e2e44835478382636d357f2fe4898cc921f6151b
service:
  main:
    ports:
      main:
        port: 7777
        protocol: udp
        targetPort: 7777
  queryport:
    enabled: true
    ports:
      queryport:
        enabled: true
        port: 27015
        protocol: udp
        targetPort: 27015
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env:
          GAME_ID: "489650 "
          GAME_PARAMS: ""
          VALIDATE: false
          USERNAME: ""
          PASSWRD: ""
