image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/conreq
  tag: latest@sha256:4ec1a322a3bc20965e9bc675b2f4b495355ea5c783b7554f5ebc156355f1eb45
persistence:
  config:
    enabled: true
    mountPath: /config
service:
  main:
    ports:
      main:
        port: 8000
        protocol: tcp
        targetPort: 8000
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          UMASK: ""
