image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/ubuntu-xrdp
  tag: latest@sha256:929a5859c03ad430696433a5c348650a575ecc562e917d41c429e7573eb9a38f
service:
  main:
    ports:
      main:
        port: 23389
        protocol: http
        targetPort: 3389
  tcpport1:
    enabled: true
    ports:
      tcpport1:
        enabled: true
        port: 6080
        protocol: tcp
        targetPort: 6080
  tcpport2:
    enabled: true
    ports:
      tcpport2:
        enabled: true
        port: 5900
        protocol: tcp
        targetPort: 5900
persistence:
  ubuntu-xrdp:
    enabled: true
    mountPath: /home/ubuntu/unraid
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
