image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/neverwinternights-ee
  tag: latest@sha256:a1903e34cfbd20a3f972021a46704e87bf4ec2834e93da52cdf7a1fb8e4c6386
persistence:
  serverfiles:
    enabled: true
    mountPath: /nwnee
service:
  main:
    ports:
      main:
        port: 5121
        protocol: udp
        targetPort: 5121
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env:
          APWD: adminDocker
          AUTO_SAV_I: "5"
          DIFF: "1"
          ELC: "0"
          GAME_PARAMS: ""
          ILR: "0"
          LOG_LVL: "4"
          MAXLEVEL: "40"
          MAX_CLIENTS: "4"
          MINLEVEL: "1"
          MOD_NAME: ""
          ONEPARTY: "0"
          PAUSEAPLAY: "0"
          PPW: Docker
          PUBLIC_SRV: "0"
          PVP: "0"
          RLD_W_E: "0"
          SERVERVAULT: "0"
          SRV_NAME: Docker NWNEE
          UMASK: "000"
