image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/cowyo
  tag: latest@sha256:ab25095f998a99f54388b331e60f47b8d764219d122608aefdca2ea51079e605
persistence:
  data:
    enabled: true
    mountPath: /data
service:
  main:
    ports:
      main:
        port: 8050
        protocol: tcp
        targetPort: 8050
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
