image:
  repository: tccr.io/truecharts/coupon-store
  tag: 1.3.0@sha256:329a146d81079584a2c5465be24ff826c493d3f78017a3ba58625317129b9f80
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10304
postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: coupon-store
  postgresqlDatabase: coupon-store
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          envFrom:
            - secretRef:
                name: '{{ include "tc.v1.common.names.fullname" . }}-couponstore-secret'
          command:
            - bash
            - -c
            - rm -f tmp/pids/server.pid && bundle exec rails s -p {{ .Values.service.main.ports.main.port }} -b '0.0.0.0'
