image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/aurora-files
  tag: latest@sha256:d948b8c2c24f9647351e930e17c6251eef4ff5d2cde39b4ec286f50da1b1aab9
persistence: {}
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env: {}
