image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/songkong
  tag: latest@sha256:08ec1d64a5ac7f3eec40d52e7e947ee61bf418e4476c8da5e70124827cf18e2d
persistence:
  music:
    enabled: true
    mountPath: /music
  songkongconfig:
    enabled: true
    mountPath: /songkong
service:
  main:
    ports:
      main:
        port: 4567
        protocol: tcp
        targetPort: 4567
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
