image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/imgpush
  tag: latest@sha256:c674c4ff5832e81728cb9e66521a3b0d69f339970b3ae0d5c4d7fcae01c940fe
persistence:
  storagecache:
    enabled: true
    mountPath: /cache
  storageimages:
    enabled: true
    mountPath: /images
service:
  main:
    ports:
      main:
        port: 5000
        protocol: tcp
        targetPort: 5000
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
