image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/shaarli
  tag: vmaster@sha256:628a3a2f9a8667879a75b01acf2c940874b2f8f044ebe7cdbf2d691adeeef5f3
persistence:
  cache:
    enabled: true
    mountPath: /var/www/shaarli/cache
  data:
    enabled: true
    mountPath: /var/www/shaarli/data
service:
  main:
    ports:
      main:
        port: 8000
        protocol: tcp
        targetPort: 80
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env: {}
