image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/kdenlive
  tag: latest@sha256:659b44ed98b24ac44e46e399a2168fc8a2b850468b217c75f039f8b5308c7b51
persistence:
  config:
    enabled: true
    mountPath: /config
service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          KEYBOARD: ""
          SUBFOLDER: ""
          UMASK: ""
