image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/livebook
  tag: latest@sha256:5083b5d5cc02f9698c040f568091c1fb46a0880cfdaa62b6584fb5b08b78ee3e
persistence:
  data:
    enabled: true
    mountPath: /data
service:
  main:
    ports:
      main:
        port: 8787
        protocol: tcp
        targetPort: 8080
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          LIVEBOOK_PASSWORD: livebookiscool
