image:
  repository: tccr.io/truecharts/qwantify
  pullPolicy: IfNotPresent
  tag: 20.04.0@sha256:ba9b1070f8f5179c082ffdcf1f390de72e33688a9fef1c884461c58567aa9378
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8080
        port: 10603
persistence:
  games:
    enabled: true
    mountPath: /games
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        env:
          APPPATH: "/games"
          APPFILE: "/game.exe"
