image:
  repository: tccr.io/truecharts/rflood
  pullPolicy: IfNotPresent
  tag: latest@sha256:43e4e5cf81418d6288d53565c5d20267e4adf76614290da1ea363819f0c8d769
service:
  main:
    ports:
      main:
        port: 3000
        protocol: http
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          FLOOD_AUTH: false
