image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/mordhau
  tag: latest@sha256:a3a4a62f7191cb844b535101ebaf567933ebac42f9462a7dfb4af011da5e6b30
service:
  main:
    ports:
      main:
        port: 7777
        protocol: udp
        targetPort: 7777
  beaconport:
    enabled: true
    ports:
      beaconport:
        enabled: true
        port: 15000
        protocol: udp
        targetPort: 15000
  udp:
    enabled: true
    ports:
      udp:
        enabled: true
        port: 27015
        protocol: udp
        targetPort: 27015
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env:
          BEACON_PORT: "15000"
          GAME_ID: "629800"
          GAME_PARAMS: ""
          GAME_PORT: "7777"
          QUERY_PORT: "27015"
          VALIDATE: false
          USERNAME: ""
          PASSWRD: ""
