image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/tasmocompiler
  tag: latest@sha256:bee39f4acdec80f438a00c1f90281a04686d6f6b93ae316005c257ce14f88f35
persistence: {}
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        env: {}
