image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/redm
  tag: latest@sha256:2c7101d825dab1bcbd377a226213b0642fb512fe714eb85b575e269710df7e2b
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
service:
  main:
    ports:
      main:
        port: 9016
        protocol: http
        targetPort: 8080
  tcp1:
    enabled: true
    ports:
      tcp1:
        enabled: true
        port: 30110
        protocol: tcp
        targetPort: 30110
  tcp2:
    enabled: true
    ports:
      tcp2:
        enabled: true
        port: 30120
        protocol: tcp
        targetPort: 30120
  udp1:
    enabled: true
    ports:
      udp1:
        enabled: true
        port: 30110
        protocol: udp
        targetPort: 30110
  udp2:
    enabled: true
    ports:
      udp2:
        enabled: true
        port: 30120
        protocol: udp
        targetPort: 30120
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        env:
          GAME_CONFIG: server.cfg
          MANUAL_UPDATES: ""
          SERVER_KEY: ""
          SRV_ADR: https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/
          SRV_NAME: ""
          START_VARS: ""
